backend:
  name: git-gateway
  branch: master


  media_folder: "static/img"
  public_folder: "img"

  collections:
    - name: "thoughts"
      label: "thoughts"
      folder: "content"
      create: true
      slug: "{{year}}-{{slug}}"
      fields: 
        - {label: "Title", name: "title", widget: "string", required: true}